# Generated by Django 3.2.9 on 2021-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobject',
            name='pic',
            field=models.ImageField(default=None, upload_to='icon/', verbose_name='Хранит иконку профиля пользователя'),
        ),
    ]
