# Generated by Django 3.2.9 on 2021-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_userobject_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobject',
            name='pic',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Хранит ссылку на иконку профиля пользователя'),
        ),
    ]
